# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique_for_date='n_date')),
                ('n_content', models.TextField()),
                ('n_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-n_date',),
            },
        ),
    ]
