# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quizNo', models.IntegerField()),
                ('order', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('firstAnswer', models.CharField(max_length=50)),
                ('secondAnswer', models.CharField(max_length=50)),
                ('thirdAnswer', models.CharField(max_length=50)),
                ('fourthAnswer', models.CharField(max_length=50)),
                ('correctAnswer', models.IntegerField()),
            ],
            options={
                'db_table': 'Question',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quizNo', models.IntegerField(primary_key=True, serialize=False)),
                ('courseNo', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'Quiz',
            },
        ),
    ]
