# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_table',
            fields=[
                ('subject_id', models.CharField(default='000', max_length=4, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(default='abc', max_length=8)),
                ('subject_details', models.CharField(default='abc', max_length=20)),
            ],
        ),
    ]
