# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_table',
            name='subject_university',
            field=models.CharField(default='USYD', max_length=20),
        ),
    ]
