# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 05:43
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', ckeditor.fields.RichTextField()),
                ('A_date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('allow', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('A_date',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q_title', models.CharField(max_length=200)),
                ('Q_des', ckeditor.fields.RichTextField()),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=300, unique_for_date='create')),
                ('Q_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20)),
                ('likes_num', models.IntegerField(default=0)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Courses_table')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-create',),
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='ans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='subject.Question'),
        ),
    ]
